=== alexshvedov161/JD2018-03-22/src/by/it/shvedov/jd02_07/BooksStore/person.dtd
<!ELEMENT Persons (Person)+>
<!ELEMENT Person (Email,Nickname,Password,Descriptions)>
 <!ELEMENT Email (#PCDATA)>
<!ELEMENT Nickname (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Descriptions (Description)+)>
<!ELEMENT Description (Name,Genre,Author,Released)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Released (#PCDATA)>

=== alexshvedov161/JD2018-03-22/src/by/it/shvedov/jd02_07/persons+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Persons SYSTEM "person.dtd">
<Persons>
    <Person>
    <Email>cloud@mail.ru</Email>
   <Nickname>cloud</Nickname>
    <Password>12345</Password>
    <Ads>
        <Ad>
            <Description>451 градус по Фаренгейту</Description>
            <Genre>научно-фантастический роман-антиутопия</Genre>
           <Author>Рэя Брэдбери</Author>
            <Released> 1953 </Released>
        </Ad>
        <Ad>
            <Description>Три мушкетёра</Description>
            <Genre> историко-приключенческий роман</Genre>
            <Author>Александр Дюма</Author>
            <Released>1844</Released>
        </Ad>
    </Ads>
    </Person>
</Persons>

=== alexshvedov161/JD2018-03-22/src/by/it/shvedov/jd02_07/BooksStore/persons+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Persons SYSTEM "person.dtd">
<Persons>
    <Person>
    <Email>cloud@mail.ru</Email>
   <Nickname>cloud</Nickname>
    <Password>12345</Password>
    <Descriptions>
        <Description>
            <Name>451 градус по Фаренгейту</Name>
            <Genre>научно-фантастический роман-антиутопия</Genre>
           <Author>Рэя Брэдбери</Author>
            <Released> 1953 </Released>
        </Description>
        <Description>
            <Name>Три мушкетёра</Name>
            <Genre> историко-приключенческий роман</Genre>
            <Author>Александр Дюма</Author>
            <Released>1844</Released>
        </Description>
    </Descriptions>
    </Person>
</Persons>
