=== alexshvedov161/JD2018-03-22/src/by/it/poprugo/jd02_07_mine/Order.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/akhmelev"
        xmlns:mns="http://it-academy.by/akhmelev"
        elementFormDefault="qualified">
    <element name="Orders">
        <complexType>
            <sequence>
                <element name="Person"
                    type="mns:Person"
                    minOccurs="1"
                    maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Person">
        <sequence>
                <element name="Email" type="string"/>
                <element name="Nickname" type="string"/>
                <element name="Password" type="string"/>
                <element name="Contract" type="mns:Contract" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
    </complexType>

    <!--   -->
    <complexType name="Contract">
        <sequence>
            <element name="Model" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="Name" type="string"/>
            <element name="Address" type="string"/>
            <element name="Phone" type="string"/>
            <element name="Number" type="string"/>
            <element name="DataContr" type="string"/>
            <element name="Price" type="positiveInteger"/>
            <element name="KeyMoney" type="positiveInteger"/>
            <element name="Production" type="mns:Production"/>
        </sequence>
    </complexType>

    <complexType name="Production">
        <sequence>
            <element name="Measure" type="string"/>
            <element name="InProduction" type="string"/>
            <element name="GetMaterials" type="string"/>
            <element name="Fitting" type="string"/>
            <element name="Refund" type="string"/>
        </sequence>
    </complexType>
</schema>

=== alexshvedov161/JD2018-03-22/src/by/it/poprugo/jd02_07_mine/Order+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Orders xmlns="http://it-academy.by/akhmelev"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://it-academy.by/akhmelev Order.xsd"
>
    <Person>
        <Email>test123@mail.ru</Email>
        <Nickname>Test123</Nickname>
        <Password>qwerty</Password>
        <Contract>
            <Model>wardrobe_1250_600_BS_V350</Model>
            <Name>Ivan</Name>
            <Address>Minsk, Kolasa, 8-35</Address>
            <Phone>33-525-33</Phone>
            <Number>W_18_05_18_1</Number>
            <DataContr>2018 may 18</DataContr>
            <Price>620</Price>
            <KeyMoney>350</KeyMoney>
            <Production>
                <Measure>2018 may 18</Measure>
                <InProduction>2018 may 21</InProduction>
                <GetMaterials>2018 may 25</GetMaterials>
                <Fitting>2018 may 26</Fitting>
                <Refund>270</Refund>
            </Production>
        </Contract>
    </Person>


    <Person>
        <Email>test321@mail.ru</Email>
        <Nickname>Test321</Nickname>
        <Password>qwerty</Password>
        <Contract>
            <Model>wardrobe_900_550_BI</Model>
            <Name>Petr</Name>
            <Address>Minsk, Philimonovd, 89-359</Address>
            <Phone>35-525-53</Phone>
            <Number>W_18_05_18_2</Number>
            <DataContr>2018 may 18</DataContr>
            <Price>350</Price>
            <KeyMoney>170</KeyMoney>
            <Production>
                <Measure>2018 may 18</Measure>
                <InProduction>2018 may 21</InProduction>
                <GetMaterials>2018 may 25</GetMaterials>
                <Fitting>2018 may 26</Fitting>
                <Refund>180</Refund>
            </Production>
        </Contract>
    </Person>


</Orders>
