=== alexshvedov161/JD2018-03-22/src/by/it/verishko/jd02_07/Store/Store.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email, Nickname, Password, Goods)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Goods (Product)+>
        <!ELEMENT Product (Name, Description, Price)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>
        <!ATTLIST Price currency PCDATA>

=== alexshvedov161/JD2018-03-22/src/by/it/verishko/jd02_07/Store/Store+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Persons SYSTEM "Store.dtd">
<Persons>
    <Person>
        <Email>test@mail.ru</Email>
        <Nickname>test123</Nickname>
        <Password>qwerty</Password>
        <Goods>
            <Product>
                <Name>Кофемолка</Name>
                <Description>Мелет кофе</Description>
                <Price currency="BYN">22</Price>
            </Product>
            <Product>
                <Name>Чайник</Name>
                <Description>Греет воду</Description>
                <Price currency="BYN">33</Price>
            </Product>
        </Goods>
    </Person>
    <Person>
        <Email>test2@mail.ru</Email>
        <Nickname>test567</Nickname>
        <Password>qwerty</Password>
        <Goods>
            <Product>
                <Name>Утюг</Name>
                <Description>Гладит одежду</Description>
                <Price currency="BYN">44</Price>
            </Product>
        </Goods>
    </Person>
</Persons>
