=== alexshvedov161/JD2018-03-22/src/by/it/poprugo/jd02_07/Person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- поменяли идентификатор у targetNamespace -->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09.poprugo.it.by"
        xmlns:tns="http://jd02_09.poprugo.it.by"
        elementFormDefault="qualified">
    <!-- всё. схему описали-->

    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person"
                         type="tns:Person"
                         minOccurs="1"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"/>
            <element name="Nikname" type="string"/>
            <element name="Password" type="string"/>
            <element name="Ads" type="tns:Ads"/>
            <!-- остальные-->
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="Ad" type="tns:Ad"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Adress" type="string"/>
            <element name="Floor" type="positiveInteger"/>
            <element name="Floors" type="positiveInteger"/>
            <element name="Square" type="string"/>
            <element name="Price" type="positiveInteger"/>
            <!-- <element name="Price" type="tns:Price"/> -->
        </sequence>
    </complexType>
    <!-- <complexType name="Price">
        <sequence>
            <attribute name="Ad" type="string"/>
            <element name="Price" type="positiveInteger"/>
        </sequence>
    </complexType> -->
</schema>

=== alexshvedov161/JD2018-03-22/src/by/it/poprugo/jd02_07/Person+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Persons xmlns="http://jd02_09.poprugo.it.by"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09.poprugo.it.by Person.xsd"
>
    <Person>
        <Email>test123@mail.ru</Email>
        <Nikname>Test123</Nikname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>Квартира в центре</Description>
                <Adress>Минск, ул Сурганова, 62</Adress>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55.5</Square>
                <Price>80000</Price> <!-- <Price currancy="$">80000</Price> -->
            </Ad>
            <!-- <Ad>
                <Description>Квартира в центре</Description>
                <Adress>Минск, ул Коласа, 8</Adress>
                <Floor>5</Floor>
                <Floors>5</Floors>
                <Square>63</Square>
                <Price>125000</Price> //<Price currancy="$">125000</Price> //
            </Ad>-->
        </Ads>
    </Person>

    <Person>
        <Email>test123@mail.ru</Email>
        <Nikname>Test123</Nikname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>Квартира в центре</Description>
                <Adress>Пинск, ул Ленина, 80</Adress>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>53.0</Square>
                <Price>62000</Price> <!-- <Price currancy="$">62000</Price> -->
            </Ad>
        </Ads>
    </Person>

</Persons>
