=== alexshvedov161/JD2018-03-22/src/by/it/verishko/jd02_07/Person.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email, Nickname, Password, Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description, Address, Floor, Floors, Square, Price)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT Floors (#PCDATA)>
        <!ELEMENT Square (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>
        <!ATTLIST Price currency PCDATA>

=== alexshvedov161/JD2018-03-22/src/by/it/akhmelev/jd02_07/Person+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Persons SYSTEM "Person.dtd">
<Persons>
    <Person>
        <Email>test123@mail.ru</Email>
        <Nickname>Test123</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>Квартира в центре</Description>
                <Address>Минск, ул. Сухарево, 4 кв.23</Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55</Square>
                <Price currency="$$$">77000</Price>
            </Ad>
            <Ad>
                <Description>Квартира в центре</Description>
                <Address>Минск, ул. Сухарево, 4 кв.24</Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55</Square>
                <Price currency="$$$">77000</Price>
            </Ad>
        </Ads>


        <Email>test5673@mail.ru</Email>
        <Nickname>Test567</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>Квартира в центре</Description>
                <Address>Пинск, ул. Ленина, 1 кв.1</Address>
                <Floor>4</Floor>
                <Floors>9</Floors>
                <Square>45.5</Square>
                <Price currency="$$$">77000</Price>
            </Ad>
        </Ads>
    </Person>
</Persons>

=== alexshvedov161/JD2018-03-22/src/by/it/poprugo/jd02_07/Person+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Persons SYSTEM "Person.dtd">
<Persons>
    <Person>
        <Email>test123@mail.ru</Email>
        <Nickname>Test123</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>Квартира в центре</Description>
                <Adress>Минск, ул Сурганова, 62</Adress>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55.5</Square>
                <Price>80000</Price>
                <!-- <Price currency="$">80000</Price> -->
            </Ad>
            <Ad>
                <Description>Квартира в центре</Description>
                <Adress>Минск, ул Коласа, 8</Adress>
                <Floor>5</Floor>
                <Floors>5</Floors>
                <Square>63</Square>
                <Price>125000</Price>
                <!-- <Price currency="$">125000</Price> -->
            </Ad>
        </Ads>
    </Person>

    <Person>
        <Email>test123@mail.ru</Email>
        <Nickname>Test123</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>Квартира в центре</Description>
                <Adress>Пинск, ул Ленина, 80</Adress>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>53.0</Square>
                <Price>62000</Price>
                <!-- <Price currency="$">62000</Price> -->
            </Ad>
        </Ads>
    </Person>

</Persons>

=== alexshvedov161/JD2018-03-22/src/by/it/danilevich/jd02_07/Person.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Persons SYSTEM "Person.dtd">
<Persons>
    <Person>
        <Email>s@mail.ru</Email>
        <Nickname>Us1</Nickname>
        <Password>123</Password>
        <Ads>
            <Ad>
                <Description>Квартира в центре</Description>
                <Address>ул.Москвоская, д.22</Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55</Square>
                <Price currency="$$$">77000</Price>

            </Ad>
            <Ad>
                <Description>Квартира возле метро</Description>
                <Address>ул.Одоевского, д.32</Address>
                <Floor>5</Floor>
                <Floors>9</Floors>
                <Square>48</Square>
                <Price currency="$$$">50000</Price>

            </Ad>

        </Ads>
    </Person>

</Persons>
