=== alexshvedov161/JD2018-03-22/src/by/it/danilevich/jd02_07/Person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/akhmelev"
        xmlns:tns="http://it-academy.by/akhmelev"
        elementFormDefault="qualified">
    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person"
                         type="tns:Person"
                         minOccurs="1"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"/>
            <element name="Nickname" type="string"/>
            <element name="Password" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="Ad" type="tns:Ad" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Address" type="string"/>
            <element name="Floor" type="positiveInteger"/>
            <element name="Floors" type="positiveInteger"/>
            <element name="Square" type="string"/>
            <element name="Price" type="tns:Price"/>
        </sequence>
        <!-- добавление аттрибута в комплексный тип -->
        <attribute name="Rooms" type="positiveInteger" use="required"/>
    </complexType>

    <!-- добавление аттрибута в простой тип выполняется внутри комплексного -->
    <complexType name="Price">
        <simpleContent>
            <!-- описание самого простого типа -->
            <extension base="string">
                <!-- и аттрибут(ов) для тега этого типа -->
                <attribute name="currency" type="string" use="required"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== alexshvedov161/JD2018-03-22/src/by/it/verishko/jd02_07/Person+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://it-academy.by/verishko"
         xsi:schemaLocation="http://it-academy.by/verishko Person.xsd">
    <Person>
        <Email>test@mail.ru</Email>
        <Nickname>test123</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad Rooms="2">
                <Description>Квартира в центре</Description>
                <Address>Минск, ул. Сухарево, 4 кв.23</Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55.5</Square>
                <Price currency="$">77000</Price>
            </Ad>
            <Ad Rooms="3">
                <Description>Квартира в центре</Description>
                <Address>Минск, ул. Сухарево, 4 кв.24</Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55</Square>
                <Price currency="$">77000</Price>
            </Ad>
        </Ads>
    </Person>
    <Person>
        <Email>test2@mail.ru</Email>
        <Nickname>test567</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad Rooms="2">
                <Description>Квартира в центре</Description>
                <Address>Пинск, ул. Ленина, 3 кв.23</Address>
                <Floor>4</Floor>
                <Floors>5</Floors>
                <Square>55.5</Square>
                <Price currency="$">77000</Price>
            </Ad>
        </Ads>
    </Person>
</Persons>

=== alexshvedov161/JD2018-03-22/src/by/it/akhmelev/jd02_07/Person+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://jd02_09.akhmelev.it.by"
         xsi:schemaLocation="http://jd02_09.akhmelev.it.by Person.xsd">
    <Person>
        <Email>test123@mail.ru</Email>
        <Nickname>Test123</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad Rooms="2">
                <Description>Квартира в центре</Description>
                <Address>Минск, ул. Сухарево, 44 кв.23</Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55</Square>
                <Price currency="$$$">77000</Price>
            </Ad>
            <Ad Rooms="3">
                <Description>Квартира в центре</Description>
                <Address>Минск, ул. Сухарево, 4 кв.24</Address>
                <Floor>2</Floor>
                <Floors>9</Floors>
                <Square>55</Square>
                <Price currency="$$$">77000</Price>
            </Ad>
        </Ads>
    </Person>
    <Person>
        <Email>test5673@mail.ru</Email>
        <Nickname>Test567</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad Rooms="2">
                <Description>Квартира в центре</Description>
                <Address>Пинск, ул. Ленина, 1 кв.1</Address>
                <Floor>4</Floor>
                <Floors>9</Floors>
                <Square>45.5</Square>
                <Price currency="$$$">77000</Price>
            </Ad>
        </Ads>
    </Person>
</Persons>
