=== alexshvedov161/JD2018-03-22/src/by/it/uskoryaev/jd02_07/BaseFace.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT BaseFace (User)+>
<!ELEMENT User (UserID,NickName,Email,Password,FirstName,LastName,MiddleName,PhoneNumber,ChooseCar)>
<!ELEMENT UserID (#PCDATA)>
<!ELEMENT NickName (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT PhoneNumber (#PCDATA)>
<!ELEMENT ChooseCar (Car)+>

        <!ELEMENT Car (CarID,SerialNumber,Brand,Model,BodyCar,YearRelease,Color,CreateReport)>
        <!ELEMENT CarID (#PCDATA)>
        <!ELEMENT SerialNumber (#PCDATA)>
        <!ELEMENT Brand (#PCDATA)>
        <!ELEMENT Model (#PCDATA)>
        <!ELEMENT BodyCar (#PCDATA)>
        <!ELEMENT YearRelease (#PCDATA)>
        <!ELEMENT Color (#PCDATA)>
        <!ELEMENT CreateReport (Report)+>

                <!ELEMENT Report (ReportID,BrandAndModel,DataOrder,Commission,Cost,TotalCost)>
                <!ELEMENT ReportID (#PCDATA)>
                <!ELEMENT BrandAndModel (#PCDATA)>
                <!ELEMENT DataOrder (#PCDATA)>
                <!ELEMENT Commission (#PCDATA)>
                <!ATTLIST Commission summa PCDATA>
                <!ELEMENT Cost (#PCDATA)>
                <!ATTLIST Cost summa PCDATA>
                <!ELEMENT TotalCost  (#PCDATA)>
                <!ATTLIST TotalCost summa PCDATA>

=== alexshvedov161/JD2018-03-22/src/by/it/uskoryaev/jd02_07/BaseFace+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE User SYSTEM "BaseFace.dtd">
<User>
    <UserID>1</UserID>
    <NickName>LikeTester</NickName>
    <Email>test@gmail.com</Email>
    <Password>test12345</Password>
    <FirstName>Alex</FirstName>
    <LastName>Smoke</LastName>
    <MiddleName>Cooks</MiddleName>
    <PhoneNumber>804456982365</PhoneNumber>
    <ChooseCar>
        <Car>
            <CarID>1</CarID>
            <SerialNumber>2g4bs4bf4r5bb</SerialNumber>
            <Brand>Mercedes</Brand>
            <Model>S-class</Model>
            <BodyCar>Coupe</BodyCar>
            <YearRelease>2017</YearRelease>
            <Color>Black</Color>
            <CreateReport>
                <Report>
                    <ReportID>1</ReportID>
                    <BrandAndModel>Mercedes S-class</BrandAndModel>
                    <DataOrder>11.04.2018</DataOrder>
                    <Commission summa="$">2</Commission>
                    <Cost summa="$">120000</Cost>
                    <TotalCost summa="$">12000</TotalCost>
                </Report>
            </CreateReport>
        </Car>
    </ChooseCar>
</User>
