=== alexshvedov161/JD2018-03-22/src/by/it/volchek/jd02_07/DoorManufacturer.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/svolchek"
        xmlns:tns="http://it-academy.by/svolchek"
        elementFormDefault="qualified">
    <element name="Managers">
        <complexType>
            <sequence>
                <element name="Manager"
                         type="tns:Manager"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Manager">
        <sequence>
            <element name="FullName" type="string"/>
            <element name="Email" type="string"/>
            <element name="Contracts"
                     type="tns:Contracts"/>
        </sequence>
    </complexType>
    <complexType name="Contracts">
        <sequence>
            <element name="Contract"
                     type="tns:Contract"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Contract">
        <sequence>
            <element name="Client" type="string"/>
            <element name="ContractNumber" type="string"/>
            <element name="Door" type="tns:Door" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <simpleType name="doorOpening">
        <restriction base="string">
            <enumeration value="Right"/>
            <enumeration value="Left"/>
        </restriction>
    </simpleType>
    <simpleType name="doorType">
        <restriction base="string">
            <enumeration value="Door"/>
            <enumeration value="Hatch"/>
        </restriction>
    </simpleType>
    <simpleType name="hDemention">
        <restriction base="integer">
            <minInclusive value="500"/>
            <maxInclusive value="2500"/>
        </restriction>
    </simpleType>
    <simpleType name="vDemention">
        <restriction base="integer">
            <minInclusive value="500"/>
            <maxInclusive value="2500"/>
        </restriction>
    </simpleType>
    <simpleType name="ralColor">
        <restriction base="string">
           <pattern value="[RAL][1-9][0][0-3][0-9]"/>
        </restriction>
    </simpleType>
    <complexType name="Door">
        <sequence>
            <element name="Type" type="tns:doorType"/>
            <element name="Price" type="positiveInteger"/>
            <element name="Quantity" type="positiveInteger"/>
            <element name="HDemention" type="tns:hDemention"/>
            <element name="VDemention" type="tns:vDemention"/>
            <element name="Opening" type="tns:doorOpening"/>
            <element name="Color" type="string"/>
        </sequence>
    </complexType>


</schema>

=== alexshvedov161/JD2018-03-22/src/by/it/volchek/jd02_07/DoorManufacturer+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>

   <Managers xmlns:="http://it-academy.by/svolchek"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://it-academy.by/svolchek DoorManufacturer.xsd">
        <Manager>
            <FullName>
                Igor Shevchenko
            </FullName>
            <Email>
                i.shevchenko@bs.by
            </Email>
            <Contracts>
                <Contract>
                    <Client>Zomex Inv.</Client>
                    <ContractNumber>23-988</ContractNumber>
                    <Door>
                        <Type>Door</Type>
                        <Price>340</Price>
                        <Quantity>4</Quantity>
                        <HDemention>900</HDemention>
                        <VDemention>2100</VDemention>
                        <Opening>Right</Opening>
                        <Color>RAL7040</Color>
                    </Door>
                    <Door>
                        <Type>Hatch</Type>
                        <Price>440</Price>
                        <Quantity>5</Quantity>
                        <HDemention>950</HDemention>
                        <VDemention>2200</VDemention>
                        <Opening>Left</Opening>
                        <Color>RAL5040</Color>
                    </Door>
                </Contract>
                <Contract>
                    <Client>SU-94</Client>
                    <ContractNumber>23-999</ContractNumber>
                    <Door>
                        <Type>Door</Type>
                        <Price>670</Price>
                        <Quantity>3</Quantity>
                        <HDemention>1100</HDemention>
                        <VDemention>2400</VDemention>
                        <Opening>Right</Opening>
                        <Color>RAL1020</Color>
                    </Door>
                </Contract>
            </Contracts>
        </Manager>
        <Manager>
            <FullName>Ivanova Diana</FullName>
            <Email>d.ivanova@bs.by</Email>
            <Contracts>
                <Contract>
                    <Client>STâ„–3</Client>
                    <ContractNumber>24-001</ContractNumber>
                    <Door>
                        <Type>Hatch</Type>
                        <Price>560</Price>
                        <Quantity>2</Quantity>
                        <HDemention>1000</HDemention>
                        <VDemention>2100</VDemention>
                        <Opening>Left</Opening>
                        <Color>RAL7001</Color>
                    </Door>
                </Contract>
            </Contracts>
        </Manager>
</Managers>
