=== alexshvedov161/JD2018-03-22/src/by/it/kirova/jd02_07/Booking.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Booking (Users+, Reservations+)>

        <!ELEMENT Users (User)+>
        <!ELEMENT User (UserId, Email, Password, FirstName, LastName, MiddleName?, Country, PhoneNumber, Hotels)>
        <!ELEMENT UserId (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT FirstName (#PCDATA)>
        <!ELEMENT LastName (#PCDATA)>
        <!ELEMENT MiddleName (#PCDATA)>
        <!ELEMENT Country (#PCDATA)>
        <!ELEMENT PhoneNumber (#PCDATA)>

        <!ELEMENT Hotels (Hotel)+>
        <!ELEMENT Hotel (HotelId, Name, Type, StarRating?, Country, City, Street, HouseNumber, ContactEmail, PhoneNumber, Rooms)>
        <!ELEMENT HotelId (#PCDATA)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Type (#PCDATA)>
        <!ELEMENT StarRating (#PCDATA)>
        <!ELEMENT City (#PCDATA)>
        <!ELEMENT Street (#PCDATA)>
        <!ELEMENT HouseNumber (#PCDATA)>
        <!ELEMENT ContactEmail (#PCDATA)>


        <!ELEMENT Rooms (Room)+>
        <!ELEMENT Room (RoomId, RoomName, RoomFactNumber?, PeopleAmount, Description?, Cost, Reservations)>
        <!ELEMENT RoomId (#PCDATA)>
        <!ELEMENT RoomName (#PCDATA)>
        <!ELEMENT RoomFactNumber (#PCDATA)>
        <!ELEMENT PeopleAmount (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Cost (#PCDATA)>
        <!ATTLIST Cost cur PCDATA>

        <!ELEMENT Reservations (Reservation)+>
        <!ELEMENT Reservation (ReservationId, ReservationDate, CheckInDate, CheckOutDate, TotalCost, PaymentStatus, UserId)>
        <!ELEMENT ReservationId (#PCDATA)>
        <!ELEMENT ReservationDate (#PCDATA)>
        <!ELEMENT CheckInDate (#PCDATA)>
        <!ELEMENT CheckOutDate (#PCDATA)>
        <!ELEMENT TotalCost (#PCDATA)>
        <!ATTLIST TotalCost cur PCDATA>
        <!ELEMENT PaymentStatus (#PCDATA)>

=== alexshvedov161/JD2018-03-22/src/by/it/kirova/jd02_07/Booking+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Booking SYSTEM "Booking.dtd">
<Booking>
    <Users>
        <User>
            <UserId>1</UserId>
            <Email>abc@gmail.com</Email>
            <Password>abc123</Password>
            <FirstName>Иван</FirstName>
            <LastName>Иванов</LastName>
            <MiddleName>Иванович</MiddleName>
            <Country>Беларусь</Country>
            <PhoneNumber>+375291111111</PhoneNumber>
            <Hotels></Hotels>
        </User>
        <User>
            <UserId>2</UserId>
            <Email>def@gmail.com</Email>
            <Password>def123</Password>
            <FirstName>Александр</FirstName>
            <LastName>Александров</LastName>
            <MiddleName>Александрович</MiddleName>
            <Country>Россия</Country>
            <PhoneNumber>+749597556983</PhoneNumber>
            <Hotels>
                <Hotel>
                    <HotelId>1</HotelId>
                    <Name>Resort Spa</Name>
                    <Type>Отель</Type>
                    <StarRating>5</StarRating>
                    <Country>Россия</Country>
                    <City>Москва</City>
                    <Street>Горького</Street>
                    <HouseNumber>82</HouseNumber>
                    <ContactEmail>spa@gmail.com</ContactEmail>
                    <PhoneNumber>+7395975339983</PhoneNumber>
                    <Rooms>
                        <Room>
                            <RoomId>2</RoomId>
                            <RoomName>Номер с односпальной кроватью</RoomName>
                            <RoomFactNumber>100</RoomFactNumber>
                            <PeopleAmount>1</PeopleAmount>
                            <Description>Завтрак включен в стоимость</Description>
                            <Cost cur="р.">15000</Cost>
                            <Reservations>
                                <Reservation>
                                    <ReservationId>3</ReservationId>
                                    <ReservationDate>2018-05-11</ReservationDate>
                                    <CheckInDate>2018-07-24</CheckInDate>
                                    <CheckOutDate>2018-07-25</CheckOutDate>
                                    <TotalCost cur="р.">15000</TotalCost>
                                    <PaymentStatus>Оплачено</PaymentStatus>
                                    <UserId>5</UserId>
                                </Reservation>
                            </Reservations>
                        </Room>
                        <Room>
                            <RoomId>4</RoomId>
                            <RoomName>Номер с 2 двуспальными кроватями</RoomName>
                            <RoomFactNumber>200</RoomFactNumber>
                            <PeopleAmount>4</PeopleAmount>
                            <Description></Description>
                            <Cost cur="$">40000</Cost>
                            <Reservations></Reservations>
                        </Room>
                    </Rooms>
                </Hotel>
            </Hotels>
        </User>
        <User>
            <UserId>3</UserId>
            <Email>xyz@gmail.com</Email>
            <Password>xyz123</Password>
            <FirstName>John</FirstName>
            <LastName>Smith</LastName>
            <MiddleName></MiddleName>
            <Country>Австрия</Country>
            <PhoneNumber>+447871234567</PhoneNumber>
            <Hotels>
                <Hotel>
                    <HotelId>2</HotelId>
                    <Name>Resort Appartment</Name>
                    <Type>Апартаменты</Type>
                    <StarRating>5</StarRating>
                    <Country>Австрия</Country>
                    <City>Вена</City>
                    <Street>Bahgasse</Street>
                    <HouseNumber>4</HouseNumber>
                    <ContactEmail>wienapart@gmail.com</ContactEmail>
                    <PhoneNumber>+4395975339983</PhoneNumber>
                    <Rooms>
                        <Room>
                            <RoomId>1</RoomId>
                            <RoomName>Апартаменты с терассой</RoomName>
                            <RoomFactNumber></RoomFactNumber>
                            <PeopleAmount>2</PeopleAmount>
                            <Description>Апартаменты в сердце Вены с терассой, двуспальной кроватью и кухней
                            </Description>
                            <Cost cur="$">450</Cost>
                            <Reservations>
                                <Reservation>
                                    <ReservationId>1</ReservationId>
                                    <ReservationDate>2018-03-14</ReservationDate>
                                    <CheckInDate>2018-07-20</CheckInDate>
                                    <CheckOutDate>2018-07-23</CheckOutDate>
                                    <TotalCost cur="$">1350</TotalCost>
                                    <PaymentStatus>Оплачено</PaymentStatus>
                                    <UserId>5</UserId>
                                </Reservation>
                                <Reservation>
                                    <ReservationId>2</ReservationId>
                                    <ReservationDate>2018-04-18</ReservationDate>
                                    <CheckInDate>2018-07-28</CheckInDate>
                                    <CheckOutDate>2018-07-29</CheckOutDate>
                                    <TotalCost cur="$">450</TotalCost>
                                    <PaymentStatus>Оплачено</PaymentStatus>
                                    <UserId>4</UserId>
                                </Reservation>
                            </Reservations>
                        </Room>
                    </Rooms>
                </Hotel>
                <Hotel>
                    <HotelId>3</HotelId>
                    <Name>Spa Appartment</Name>
                    <Type>Апартаменты</Type>
                    <StarRating>5</StarRating>
                    <Country>Австрия</Country>
                    <City>Вена</City>
                    <Street>Johann-Hoffmann Platz</Street>
                    <HouseNumber>16</HouseNumber>
                    <ContactEmail>wienapart@gmail.com</ContactEmail>
                    <PhoneNumber>+4395975339983</PhoneNumber>
                    <Rooms>
                        <Room>
                            <RoomId>3</RoomId>
                            <RoomName>Апартаменты с 2 спальнями</RoomName>
                            <RoomFactNumber></RoomFactNumber>
                            <PeopleAmount>2</PeopleAmount>
                            <Description>Апартаменты в сердце Вены с 2 двуспальными кроватями и кухней</Description>
                            <Cost cur="$">550</Cost>
                            <Reservations></Reservations>
                        </Room>
                    </Rooms>
                </Hotel>
            </Hotels>
        </User>
        <User>
            <UserId>4</UserId>
            <Email>glg@gmail.com</Email>
            <Password>glg123</Password>
            <FirstName>Петр</FirstName>
            <LastName>Петров</LastName>
            <MiddleName>Петрович</MiddleName>
            <Country>Беларусь</Country>
            <PhoneNumber>+375292222222</PhoneNumber>
            <Hotels></Hotels>
        </User>
        <User>
            <UserId>5</UserId>
            <Email>ppp@gmail.com</Email>
            <Password>ppp123</Password>
            <FirstName>Jacob</FirstName>
            <LastName>Irwin</LastName>
            <MiddleName></MiddleName>
            <Country>Польша</Country>
            <PhoneNumber>+485291111111</PhoneNumber>
            <Hotels></Hotels>
        </User>
    </Users>
</Booking>
