=== alexshvedov161/JD2018-03-22/src/by/it/romankov/jd02_07/Agent.dtd
<?xml version="1.0" encoding="Utf-8" ?>
<!ELEMENT Agents (Agent)+>
<!ELEMENT Agent (Name, Telephone, Email,Tours, Reapeted_Clients)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Tours (Tour)+>
<!ELEMENT Tour (Type, Destination, AmountOfDays,DepartureCity,Price)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Destination (#PCDATA)>
<!ELEMENT AmountOfDays (#PCDATA) >
<!ELEMENT DepartureCity (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price currency PCDATA>
<!ELEMENT Reapeted_Clients (Reapeted_Client)+>
<!ELEMENT Reapeted_Client (FirstName, Age)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT Age (#PCDATA)>

=== alexshvedov161/JD2018-03-22/src/by/it/romankov/jd02_07/Agent+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Agents SYSTEM "Agent.dtd">
<Agents>
    <Agent>
        <Name>Dmitry</Name>
        <Telephone>8956235</Telephone>
        <Email>dmitry@mail.ru</Email>
        <Tours>
            <Tour>
                <Type>Beach holidays</Type>
                <Destination> Barselona</Destination>
                <AmountOfDays>11</AmountOfDays>
                <DepartureCity>Minsk</DepartureCity>
                <Price currency="$$$">1000</Price>

            </Tour>
            <Tour>
                <Type>Shopping</Type>
                <Destination> Vilnus</Destination>
                <AmountOfDays>1</AmountOfDays>
                <DepartureCity>Minsk</DepartureCity>
                <Price currency="$$$">30</Price>
            </Tour>
        </Tours>
        <Reapeted_Clients>
            <Reapeted_Client>
            <FirstName> Nikita </FirstName>
            <Age>29</Age>
            </Reapeted_Client>
            <Reapeted_Client>
            <FirstName> Anna </FirstName>
            <Age>29</Age>
            </Reapeted_Client>
        </Reapeted_Clients>
    </Agent>
    <Agent>
        <Name>Alisa</Name>
        <Telephone>7896542</Telephone>
        <Email>alisa@mail.ru</Email>
        <Tours>
            <Tour>
                <Type>Excursion</Type>
                <Destination> Krakov</Destination>
                <AmountOfDays>4</AmountOfDays>
                <DepartureCity>Minsk</DepartureCity>
                <Price currency="$$$">120</Price>
            </Tour>
        </Tours>
        <Reapeted_Clients>
            <Reapeted_Client>
            <FirstName> Ilya </FirstName>
            <Age>31</Age>
            </Reapeted_Client>
        </Reapeted_Clients>
    </Agent>
</Agents>
