=== alexshvedov161/JD2018-03-22/src/by/it/romankov/jd02_07/Agent.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/romankov"
        xmlns:tns="http://it-academy.by/romankov"
        elementFormDefault="qualified">
    <element name="Agents">
        <complexType>
            <sequence>
                <element name="Agent"
                         type="tns:Agent"
                         minOccurs="1"
                         maxOccurs="unbounded">

                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Agent">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Telephone" type="positiveInteger"/>
            <element name="Email" type="string"/>
            <element name="Tours" type="tns:Tours"/>
            <element name="Reapeted_Clients" type="tns:Reapeted_Clients"/>
        </sequence>
    </complexType>
<complexType name="Tours">
    <sequence>
        <element name="Tour" type="tns:Tour" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
</complexType>
    <complexType name="Tour">
        <sequence>
            <element name="Type" type="string"/>
            <element name="Destination" type="string"/>
            <element name="AmountOfDays" type="positiveInteger"/>
            <element name="DepartureCity" type="string"/>
            <element name="Price" type="tns:Price"/>
        </sequence>
    </complexType>
    <complexType name="Reapeted_Clients">
        <sequence>
            <element name="Reapeted_Client" type="tns:Reapeted_Client" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Reapeted_Client">
        <sequence>
            <element name="FirstName" type="string"/>
            <element name="Age" type="positiveInteger"/>
        </sequence>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="string">
                <attribute name="currency" type="string" use="optional" default="$$$"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== alexshvedov161/JD2018-03-22/src/by/it/romankov/jd02_07/Agent+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Agents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://it-academy.by/romankov"
         xsi:schemaLocation="http://it-academy.by/romankov Agent.xsd">
    <Agent>
        <Name>Dmitry</Name>
        <Telephone>8956235</Telephone>
        <Email>dmitry@mail.ru</Email>
        <Tours>
            <Tour>
                <Type>Beach holidays</Type>
                <Destination> Barselona</Destination>
                <AmountOfDays>11</AmountOfDays>
                <DepartureCity>Minsk</DepartureCity>
                <Price currency="uio">1000</Price>
            </Tour>
            <Tour>
                <Type>Shopping</Type>
                <Destination> Vilnus</Destination>
                <AmountOfDays>1</AmountOfDays>
                <DepartureCity>Minsk</DepartureCity>
                <Price currency="$$$">30</Price>
            </Tour>
        </Tours>
        <Reapeted_Clients>
            <Reapeted_Client>
            <FirstName> Nikita </FirstName>
            <Age>29</Age>
            </Reapeted_Client>
            <Reapeted_Client>
                <FirstName>Anna</FirstName>
                <Age>29</Age>
            </Reapeted_Client>
        </Reapeted_Clients>
    </Agent>
    <Agent>
        <Name>Alisa</Name>
        <Telephone>7896542</Telephone>
        <Email>alisa@mail.ru</Email>
        <Tours>
            <Tour>
                <Type>Excursion</Type>
                <Destination> Krakov</Destination>
                <AmountOfDays>4</AmountOfDays>
                <DepartureCity>Minsk</DepartureCity>
                <Price currency="777">120</Price>
            </Tour>
        </Tours>
        <Reapeted_Clients>
            <Reapeted_Client>
            <FirstName> Ilya </FirstName>
            <Age>31</Age>
            </Reapeted_Client>
        </Reapeted_Clients>
    </Agent>
</Agents>
